In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [2]:
df_2015 = pd.read_csv('2015.csv')
df_2016 = pd.read_csv('2016.csv')
df_2017 = pd.read_csv('2017.csv')
df_2018 = pd.read_csv('2018.csv')
df_2019 = pd.read_csv('2019.csv')
df_2020 = pd.read_csv('2020.csv')

In [3]:
df_2015.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 12 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Country                        158 non-null    object
 1   Region                         158 non-null    object
 2   Happiness Rank                 158 non-null    int64
 3   Happiness Score                158 non-null    float64
 4   Standard Error                 158 non-null    float64
 5   Economy (GDP per Capita)       158 non-null    float64
 6   Family                         158 non-null    float64
 7   Health (Life Expectancy)       158 non-null    float64
 8   Freedom                        158 non-null    float64
 9   Trust (Government Corruption)  158 non-null    float64
 10  Generosity                     158 non-null    float64
 11  Dystopia Residual              158 non-null    float64
dtypes: float64(9), int64(1), object(2)
memory usage: 14.9+ KB

In [4]:
df_2016.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Country                        157 non-null    object
 1   Region                         157 non-null    object
 2   Happiness Rank                 157 non-null    int64
 3   Happiness Score                157 non-null    float64
 4   Lower Confidence Interval      157 non-null    float64
 5   Upper Confidence Interval      157 non-null    float64
 6   Economy (GDP per Capita)       157 non-null    float64
 7   Family                         157 non-null    float64
 8   Health (Life Expectancy)       157 non-null    float64
 9   Freedom                        157 non-null    float64
 10  Trust (Government Corruption)  157 non-null    float64
 11  Generosity                     157 non-null    float64
 12  Dystopia Residual              157 non-null    float64
dtypes: float64(10), int64(1), object(2)
memory usage: 16.1+ KB

In [5]:
df_2017.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 155 entries, 0 to 154
Data columns (total 12 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Country                        155 non-null    object
 1   Happiness.Rank                 155 non-null    int64
 2   Happiness.Score                155 non-null    float64
 3   Whisker.high                   155 non-null    float64
 4   Whisker.low                    155 non-null    float64
 5   Economy..GDP.per.Capita.       155 non-null    float64
 6   Family                         155 non-null    float64
 7   Health..Life.Expectancy.       155 non-null    float64
 8   Freedom                        155 non-null    float64
 9   Generosity                     155 non-null    float64
 10  Trust..Government.Corruption.  155 non-null    float64
 11  Dystopia.Residual              155 non-null    float64
dtypes: float64(10), int64(1), object(1)
memory usage: 14.7+ KB

In [6]:
df_2018.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 9 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Overall rank                  156 non-null    int64
 1   Country or region             156 non-null    object
 2   Score                         156 non-null    float64
 3   GDP per capita                156 non-null    float64
 4   Social support                156 non-null    float64
 5   Healthy life expectancy       156 non-null    float64
 6   Freedom to make life choices  156 non-null    float64
 7   Generosity                    156 non-null    float64
 8   Perceptions of corruption     155 non-null    float64
dtypes: float64(7), int64(1), object(1)
memory usage: 11.1+ KB

In [7]:
df_2019.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 9 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Overall rank                  156 non-null    int64
 1   Country or region             156 non-null    object
 2   Score                         156 non-null    float64
 3   GDP per capita                156 non-null    float64
 4   Social support                156 non-null    float64
 5   Healthy life expectancy       156 non-null    float64
 6   Freedom to make life choices  156 non-null    float64
 7   Generosity                    156 non-null    float64
 8   Perceptions of corruption     156 non-null    float64
dtypes: float64(7), int64(1), object(1)
memory usage: 11.1+ KB

In [8]:
df_2020.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 153 entries, 0 to 152
Data columns (total 20 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Country name                                153 non-null    object
 1   Regional indicator                          153 non-null    object
 2   Ladder score                                153 non-null    float64
 3   Standard error of ladder score              153 non-null    float64
 4   upperwhisker                                153 non-null    float64
 5   lowerwhisker                                153 non-null    float64
 6   Logged GDP per capita                       153 non-null    float64
 7   Social support                              153 non-null    float64
 8   Healthy life expectancy                     153 non-null    float64
 9   Freedom to make life choices                153 non-null    float64
 10  Generosity                                  153 non-null    float64
 11  Perceptions of corruption                   153 non-null    float64
 12  Ladder score in Dystopia                    153 non-null    float64
 13  Explained by: Log GDP per capita            153 non-null    float64
 14  Explained by: Social support                153 non-null    float64
 15  Explained by: Healthy life expectancy       153 non-null    float64
 16  Explained by: Freedom to make life choices  153 non-null    float64
 17  Explained by: Generosity                    153 non-null    float64
 18  Explained by: Perceptions of corruption     153 non-null    float64
 19  Dystopia + residual                         153 non-null    float64
dtypes: float64(18), object(2)
memory usage: 24.0+ KB

In [9]:
#  observations:
#  1. the data fields in each dataset varies
#  2. there is no null values within the variables
#  Since the data fields vary, we need to standardize the data before we can combine the datasets

In [10]:
df_2015.head()

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176

In [11]:
df_2016.head()

,Country,Region,Happiness Rank,Happiness Score,Lower Confidence Interval,Upper Confidence Interval,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Denmark,Western Europe,1,7.526,7.460,7.592,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171,2.73939
1,Switzerland,Western Europe,2,7.509,7.428,7.590,1.52733,1.14524,0.86303,0.58557,0.41203,0.28083,2.69463
2,Iceland,Western Europe,3,7.501,7.333,7.669,1.42666,1.18326,0.86733,0.56624,0.14975,0.47678,2.83137
3,Norway,Western Europe,4,7.498,7.421,7.575,1.57744,1.12690,0.79579,0.59609,0.35776,0.37895,2.66465
4,Finland,Western Europe,5,7.413,7.351,7.475,1.40598,1.13464,0.81091,0.57104,0.41004,0.25492,2.82596

In [12]:
df_2017.head()

,Country,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
0,Norway,1,7.537,7.594445,7.479556,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027
1,Denmark,2,7.522,7.581728,7.462272,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707
2,Iceland,3,7.504,7.622030,7.385970,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715
3,Switzerland,4,7.494,7.561772,7.426227,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007,2.276716
4,Finland,5,7.469,7.527542,7.410458,1.443572,1.540247,0.809158,0.617951,0.245483,0.382612,2.430182

In [13]:
df_2018.head()

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.632,1.305,1.592,0.874,0.681,0.202,0.393
1,2,Norway,7.594,1.456,1.582,0.861,0.686,0.286,0.340
2,3,Denmark,7.555,1.351,1.590,0.868,0.683,0.284,0.408
3,4,Iceland,7.495,1.343,1.644,0.914,0.677,0.353,0.138
4,5,Switzerland,7.487,1.420,1.549,0.927,0.660,0.256,0.357

In [14]:
df_2019.head()

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341
3,4,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118
4,5,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298

In [15]:
df_2020.head()

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,Western Europe,7.8087,0.031156,7.869766,7.747634,10.639267,0.954330,71.900825,0.949172,-0.059482,0.195445,1.972317,1.285190,1.499526,0.961271,0.662317,0.159670,0.477857,2.762835
1,Denmark,Western Europe,7.6456,0.033492,7.711245,7.579955,10.774001,0.955991,72.402504,0.951444,0.066202,0.168489,1.972317,1.326949,1.503449,0.979333,0.665040,0.242793,0.495260,2.432741
2,Switzerland,Western Europe,7.5599,0.035014,7.628528,7.491272,10.979933,0.942847,74.102448,0.921337,0.105911,0.303728,1.972317,1.390774,1.472403,1.040533,0.628954,0.269056,0.407946,2.350267
3,Iceland,Western Europe,7.5045,0.059616,7.621347,7.387653,10.772559,0.974670,73.000000,0.948892,0.246944,0.711710,1.972317,1.326502,1.547567,1.000843,0.661981,0.362330,0.144541,2.460688
4,Norway,Western Europe,7.4880,0.034837,7.556281,7.419719,11.087804,0.952487,73.200783,0.955750,0.134533,0.263218,1.972317,1.424207,1.495173,1.008072,0.670201,0.287985,0.434101,2.168266

In [16]:
# Observations from the first 5 observations of each dataset
# 1. 2015, 2016 and 2017: "Country" and "Region" are available
#    2018 and 2019: Only "Country or Region" is available, Region information is not available.
#    2020: "Country Name" and "Regional Indicator" are available.
#    Standardization required: 
#    i. Rename "Country or Region" to "Country" for 2018 and 2019 and create the column "Region"
#    ii. Rename "Country Name" and "Regional Indicator" to "Country" and "Region" respectively for 2020
# 2. 2015, 2016: "Happiness Rank" and "Happiness Score" are available
#    2017: "Happiness.Rank" and "Happiness.Score" are available
#    2018, 2019: "Overall rank" and "Score" are available
#    2020: Only "Ladder score" is available
#    Standardization required: 
#    i. Rename "Happiness.Rank" and "Happiness.Score" to "Happiness Rank" and "Happiness Score" respectively for 2017
#    ii. Rename "Overall rank" and "Score" to "Happiness Rank" and "Happiness Score" respectively for 2018 and 2019
#    iii. Rename "Ladder score" to "Happiness Score" and Create a column "Happiness Rank" for 202
# 3. 2015: "Standard Error"
#    2020: "Standard error of ladder score"
#    2016: "Lower Confidence Interval" and "Upper Confidence Interval"
#    2017: "Whisker.high" and "Whisker.low"
#    2020: "upperwhisker" and "Lowerwhisker"
#    Standardization required: 
#    We will drop these variables, because the variable may only be available in one or two datasets only
# 4. For 2015-2019, the rest of the variables are the components of the happiness score
#    For 2020, there are a lot more variables are available, we will look into in a bit
#    Standardization required for 2015-2019
#    "Economy (GDP per Capita)", "Economy..GDP.per.Capita.", "GDP per capita" -> "GDP per capita"
#    "Family" is available in from 2015 to 2017 only -> Create a blank column "Family" for 2018 and 2019
#    "Social support" is available in from 2018 to 2019 only -> Create a blank column "Social support" for 2015 and 2017
#    "Health (Life Expectancy)", "Health..Life.Expectancy.", "Healthy life expectancy" -> "Healthy life expectancy"
#    "Freedom","Freedom to make life choices" -> "Freedom to make life choices"
#    "Trust (Government Corruption)","Trust..Government.Corruption.", "Perceptions of corruption" - > "Perceptions of corruption"
#    "Dystopia Residual" is available in from 2015 to 2017 only -> Create a blank column "Dystopia Residual" for 2018 and 2019
# 5. For 2020 dataset, for example, there are 2 variables, "Social support" and "Explained by: Social support"
#    Actions required:
#    - We need to determine which variable is used to calculate the happiness score
#    - standardize the naming

In [17]:
clean_df_2015 = df_2015.rename(columns = {'Economy (GDP per Capita)': 'GDP per capita', 'Health (Life Expectancy)': 'Healthy life expectancy', 'Trust (Government Corruption)': 'Perceptions of corruption'}, inplace = False)
clean_df_2015 = clean_df_2015.drop(columns=['Standard Error'])
clean_df_2015.head()

,Country,Region,Happiness Rank,Happiness Score,GDP per capita,Family,Healthy life expectancy,Freedom,Perceptions of corruption,Generosity,Dystopia Residual
0,Switzerland,Western Europe,1,7.587,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,Western Europe,2,7.561,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,Western Europe,3,7.527,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,Norway,Western Europe,4,7.522,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,Canada,North America,5,7.427,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176

In [18]:
clean_df_2016 = df_2016.rename(columns = {'Economy (GDP per Capita)': 'GDP per capita', 'Health (Life Expectancy)': 'Healthy life expectancy', 'Trust (Government Corruption)': 'Perceptions of corruption'}, inplace = False)
clean_df_2016 = clean_df_2016.drop(columns=['Lower Confidence Interval','Upper Confidence Interval'])
clean_df_2016.head()

,Country,Region,Happiness Rank,Happiness Score,GDP per capita,Family,Healthy life expectancy,Freedom,Perceptions of corruption,Generosity,Dystopia Residual
0,Denmark,Western Europe,1,7.526,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171,2.73939
1,Switzerland,Western Europe,2,7.509,1.52733,1.14524,0.86303,0.58557,0.41203,0.28083,2.69463
2,Iceland,Western Europe,3,7.501,1.42666,1.18326,0.86733,0.56624,0.14975,0.47678,2.83137
3,Norway,Western Europe,4,7.498,1.57744,1.12690,0.79579,0.59609,0.35776,0.37895,2.66465
4,Finland,Western Europe,5,7.413,1.40598,1.13464,0.81091,0.57104,0.41004,0.25492,2.82596

In [19]:
clean_df_2017 = df_2017.rename(columns = {'Happiness.Rank': 'Happiness Rank', 'Happiness.Score': 'Happiness Score', 'Economy..GDP.per.Capita.': 'GDP per capita', 'Health..Life.Expectancy.': 'Healthy life expectancy','Trust..Government.Corruption.': 'Perceptions of corruption','Dystopia.Residual': 'Dystopia Residual'}, inplace = False)
clean_df_2017 = clean_df_2017.drop(columns=['Whisker.high','Whisker.low'])
clean_df_2017.head()

,Country,Happiness Rank,Happiness Score,GDP per capita,Family,Healthy life expectancy,Freedom,Generosity,Perceptions of corruption,Dystopia Residual
0,Norway,1,7.537,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027
1,Denmark,2,7.522,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707
2,Iceland,3,7.504,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715
3,Switzerland,4,7.494,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007,2.276716
4,Finland,5,7.469,1.443572,1.540247,0.809158,0.617951,0.245483,0.382612,2.430182

In [20]:
clean_df_2018 = df_2018.rename(columns = {'Country or region': 'Country', 'Overall rank': 'Happiness Rank','Score': 'Happiness Score', 'Economy..GDP.per.Capita.': 'GDP per capita', 'Health..Life.Expectancy.': 'Healthy life expectancy','Trust..Government.Corruption.': 'Perceptions of corruption','Dystopia.Residual': 'Dystopia Residual'}, inplace = False)
cols_18 = clean_df_2018.columns.tolist()
cols_18.insert(0, cols_18.pop(cols_18.index('Country')))
clean_df_2018 = clean_df_2018.reindex(columns= cols_18)
clean_df_2018.head()

,Country,Happiness Rank,Happiness Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,Finland,1,7.632,1.305,1.592,0.874,0.681,0.202,0.393
1,Norway,2,7.594,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,3,7.555,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,4,7.495,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,5,7.487,1.420,1.549,0.927,0.660,0.256,0.357

In [21]:
clean_df_2019 = df_2019.rename(columns = {'Country or region': 'Country', 'Overall rank': 'Happiness Rank','Score': 'Happiness Score', 'Economy..GDP.per.Capita.': 'GDP per capita', 'Health..Life.Expectancy.': 'Healthy life expectancy','Trust..Government.Corruption.': 'Perceptions of corruption','Dystopia.Residual': 'Dystopia Residual'}, inplace = False)
cols_19 = clean_df_2019.columns.tolist()
cols_19.insert(0, cols_19.pop(cols_19.index('Country')))
clean_df_2019 = clean_df_2019.reindex(columns= cols_19)
clean_df_2019.head()

,Country,Happiness Rank,Happiness Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,Finland,1,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,Denmark,2,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,Norway,3,7.554,1.488,1.582,1.028,0.603,0.271,0.341
3,Iceland,4,7.494,1.380,1.624,1.026,0.591,0.354,0.118
4,Netherlands,5,7.488,1.396,1.522,0.999,0.557,0.322,0.298

In [22]:
# Check whick variables are the components of the Happiness Score in 2020 dataset
df_2020.head()

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,Western Europe,7.8087,0.031156,7.869766,7.747634,10.639267,0.954330,71.900825,0.949172,-0.059482,0.195445,1.972317,1.285190,1.499526,0.961271,0.662317,0.159670,0.477857,2.762835
1,Denmark,Western Europe,7.6456,0.033492,7.711245,7.579955,10.774001,0.955991,72.402504,0.951444,0.066202,0.168489,1.972317,1.326949,1.503449,0.979333,0.665040,0.242793,0.495260,2.432741
2,Switzerland,Western Europe,7.5599,0.035014,7.628528,7.491272,10.979933,0.942847,74.102448,0.921337,0.105911,0.303728,1.972317,1.390774,1.472403,1.040533,0.628954,0.269056,0.407946,2.350267
3,Iceland,Western Europe,7.5045,0.059616,7.621347,7.387653,10.772559,0.974670,73.000000,0.948892,0.246944,0.711710,1.972317,1.326502,1.547567,1.000843,0.661981,0.362330,0.144541,2.460688
4,Norway,Western Europe,7.4880,0.034837,7.556281,7.419719,11.087804,0.952487,73.200783,0.955750,0.134533,0.263218,1.972317,1.424207,1.495173,1.008072,0.670201,0.287985,0.434101,2.168266

In [23]:
col_list = df_2020.columns.tolist()
col_list

['Country name',
 'Regional indicator',
 'Ladder score',
 'Standard error of ladder score',
 'upperwhisker',
 'lowerwhisker',
 'Logged GDP per capita',
 'Social support',
 'Healthy life expectancy',
 'Freedom to make life choices',
 'Generosity',
 'Perceptions of corruption',
 'Ladder score in Dystopia',
 'Explained by: Log GDP per capita',
 'Explained by: Social support',
 'Explained by: Healthy life expectancy',
 'Explained by: Freedom to make life choices',
 'Explained by: Generosity',
 'Explained by: Perceptions of corruption',
 'Dystopia + residual']

In [24]:
col_list_1 = col_list[6:13]
col_list_2 = col_list[13:20]
print(col_list_1)
print(col_list_2)

['Logged GDP per capita', 'Social support', 'Healthy life expectancy', 'Freedom to make life choices', 'Generosity', 'Perceptions of corruption', 'Ladder score in Dystopia']
['Explained by: Log GDP per capita', 'Explained by: Social support', 'Explained by: Healthy life expectancy', 'Explained by: Freedom to make life choices', 'Explained by: Generosity', 'Explained by: Perceptions of corruption', 'Dystopia + residual']

In [25]:
df_2020["sum_1"] = round(df_2020[col_list_1].sum(axis=1),4)
df_2020["sum_2"] = round(df_2020[col_list_2].sum(axis=1),4)
df_2020

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,...,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual,sum_1,sum_2
0,Finland,Western Europe,7.8087,0.031156,7.869766,7.747634,10.639267,0.954330,71.900825,0.949172,...,1.972317,1.285190,1.499526,0.961271,0.662317,0.159670,0.477857,2.762835,86.5519,7.8087
1,Denmark,Western Europe,7.6456,0.033492,7.711245,7.579955,10.774001,0.955991,72.402504,0.951444,...,1.972317,1.326949,1.503449,0.979333,0.665040,0.242793,0.495260,2.432741,87.2909,7.6456
2,Switzerland,Western Europe,7.5599,0.035014,7.628528,7.491272,10.979933,0.942847,74.102448,0.921337,...,1.972317,1.390774,1.472403,1.040533,0.628954,0.269056,0.407946,2.350267,89.3285,7.5599
3,Iceland,Western Europe,7.5045,0.059616,7.621347,7.387653,10.772559,0.974670,73.000000,0.948892,...,1.972317,1.326502,1.547567,1.000843,0.661981,0.362330,0.144541,2.460688,88.6271,7.5045
4,Norway,Western Europe,7.4880,0.034837,7.556281,7.419719,11.087804,0.952487,73.200783,0.955750,...,1.972317,1.424207,1.495173,1.008072,0.670201,0.287985,0.434101,2.168266,88.5669,7.4880
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,Central African Republic,Sub-Saharan Africa,3.4759,0.115183,3.701658,3.250141,6.625160,0.319460,45.200001,0.640881,...,1.972317,0.041072,0.000000,0.000000,0.292814,0.253513,0.028265,2.860198,55.7320,3.4759
149,Rwanda,Sub-Saharan Africa,3.3123,0.052425,3.415053,3.209547,7.600104,0.540835,61.098846,0.900589,...,1.972317,0.343243,0.522876,0.572383,0.604088,0.235705,0.485542,0.548445,72.3517,3.3123
150,Zimbabwe,Sub-Saharan Africa,3.2992,0.058674,3.414202,3.184198,7.865712,0.763093,55.617260,0.711458,...,1.972317,0.425564,1.047835,0.375038,0.377405,0.151349,0.080929,0.841031,67.6680,3.2992
151,South Sudan,Sub-Saharan Africa,2.8166,0.107610,3.027516,2.605684,7.425360,0.553707,51.000000,0.451314,...,1.972317,0.289083,0.553279,0.208809,0.065609,0.209935,0.111157,1.378751,62.1826,2.8166
152,Afghanistan,South Asia,2.5669,0.031311,2.628270,2.505530,7.462861,0.470367,52.590000,0.396573,...,1.972317,0.300706,0.356434,0.266052,0.000000,0.135235,0.001226,1.507236,63.7294,2.5669

In [26]:
df_2020['check_1'] = round(df_2020['Ladder score'],4)-(round(df_2020['sum_1'],4))
df_2020['check_2'] = round(df_2020['Ladder score'],4)-(round(df_2020['sum_2'],4))
df_2020

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,...,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual,sum_1,sum_2,check_1,check_2
0,Finland,Western Europe,7.8087,0.031156,7.869766,7.747634,10.639267,0.954330,71.900825,0.949172,...,1.499526,0.961271,0.662317,0.159670,0.477857,2.762835,86.5519,7.8087,-78.7432,0.0
1,Denmark,Western Europe,7.6456,0.033492,7.711245,7.579955,10.774001,0.955991,72.402504,0.951444,...,1.503449,0.979333,0.665040,0.242793,0.495260,2.432741,87.2909,7.6456,-79.6453,0.0
2,Switzerland,Western Europe,7.5599,0.035014,7.628528,7.491272,10.979933,0.942847,74.102448,0.921337,...,1.472403,1.040533,0.628954,0.269056,0.407946,2.350267,89.3285,7.5599,-81.7686,0.0
3,Iceland,Western Europe,7.5045,0.059616,7.621347,7.387653,10.772559,0.974670,73.000000,0.948892,...,1.547567,1.000843,0.661981,0.362330,0.144541,2.460688,88.6271,7.5045,-81.1226,0.0
4,Norway,Western Europe,7.4880,0.034837,7.556281,7.419719,11.087804,0.952487,73.200783,0.955750,...,1.495173,1.008072,0.670201,0.287985,0.434101,2.168266,88.5669,7.4880,-81.0789,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,Central African Republic,Sub-Saharan Africa,3.4759,0.115183,3.701658,3.250141,6.625160,0.319460,45.200001,0.640881,...,0.000000,0.000000,0.292814,0.253513,0.028265,2.860198,55.7320,3.4759,-52.2561,0.0
149,Rwanda,Sub-Saharan Africa,3.3123,0.052425,3.415053,3.209547,7.600104,0.540835,61.098846,0.900589,...,0.522876,0.572383,0.604088,0.235705,0.485542,0.548445,72.3517,3.3123,-69.0394,0.0
150,Zimbabwe,Sub-Saharan Africa,3.2992,0.058674,3.414202,3.184198,7.865712,0.763093,55.617260,0.711458,...,1.047835,0.375038,0.377405,0.151349,0.080929,0.841031,67.6680,3.2992,-64.3688,0.0
151,South Sudan,Sub-Saharan Africa,2.8166,0.107610,3.027516,2.605684,7.425360,0.553707,51.000000,0.451314,...,0.553279,0.208809,0.065609,0.209935,0.111157,1.378751,62.1826,2.8166,-59.3660,0.0
152,Afghanistan,South Asia,2.5669,0.031311,2.628270,2.505530,7.462861,0.470367,52.590000,0.396573,...,0.356434,0.266052,0.000000,0.135235,0.001226,1.507236,63.7294,2.5669,-61.1625,0.0

In [27]:
np.count_nonzero(df_2020['check_1'] != 0)

153

In [28]:
np.count_nonzero(df_2020['check_2'] != 0)

0

In [29]:
# We can conclude that the below variables are the components of the happiness score
col_list_2

['Explained by: Log GDP per capita',
 'Explained by: Social support',
 'Explained by: Healthy life expectancy',
 'Explained by: Freedom to make life choices',
 'Explained by: Generosity',
 'Explained by: Perceptions of corruption',
 'Dystopia + residual']

In [30]:
clean_df_2020 = df_2020.drop(columns=['Regional indicator','Standard error of ladder score','upperwhisker','lowerwhisker','Logged GDP per capita','Social support','Healthy life expectancy','Freedom to make life choices','Generosity','Perceptions of corruption','sum_1','sum_2','check_1','check_2'])
clean_df_2020 = clean_df_2020.rename(columns = {'Country name': 'Country', 'Ladder score': 'Happiness Score', 'Explained by: Log GDP per capita': 'GDP per capita', 'Explained by: Social support': 'Social support', 'Explained by: Healthy life expectancy': 'Healthy life expectancy','Explained by: Freedom to make life choices': 'Freedom to make life choices','Explained by: Perceptions of corruption': 'Perceptions of corruption','Explained by: Generosity': 'Generosity','Dystopia + residual': 'Dystopia Residual'}, inplace = False)
clean_df_2020.head()

,Country,Happiness Score,Ladder score in Dystopia,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Dystopia Residual
0,Finland,7.8087,1.972317,1.285190,1.499526,0.961271,0.662317,0.159670,0.477857,2.762835
1,Denmark,7.6456,1.972317,1.326949,1.503449,0.979333,0.665040,0.242793,0.495260,2.432741
2,Switzerland,7.5599,1.972317,1.390774,1.472403,1.040533,0.628954,0.269056,0.407946,2.350267
3,Iceland,7.5045,1.972317,1.326502,1.547567,1.000843,0.661981,0.362330,0.144541,2.460688
4,Norway,7.4880,1.972317,1.424207,1.495173,1.008072,0.670201,0.287985,0.434101,2.168266

In [31]:
clean_df_2020["Happiness Rank"] = clean_df_2020["Happiness Score"].rank(ascending=False)
clean_df_2020

,Country,Happiness Score,Ladder score in Dystopia,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Dystopia Residual,Happiness Rank
0,Finland,7.8087,1.972317,1.285190,1.499526,0.961271,0.662317,0.159670,0.477857,2.762835,1.0
1,Denmark,7.6456,1.972317,1.326949,1.503449,0.979333,0.665040,0.242793,0.495260,2.432741,2.0
2,Switzerland,7.5599,1.972317,1.390774,1.472403,1.040533,0.628954,0.269056,0.407946,2.350267,3.0
3,Iceland,7.5045,1.972317,1.326502,1.547567,1.000843,0.661981,0.362330,0.144541,2.460688,4.0
4,Norway,7.4880,1.972317,1.424207,1.495173,1.008072,0.670201,0.287985,0.434101,2.168266,5.0
...,...,...,...,...,...,...,...,...,...,...,...
148,Central African Republic,3.4759,1.972317,0.041072,0.000000,0.000000,0.292814,0.253513,0.028265,2.860198,149.0
149,Rwanda,3.3123,1.972317,0.343243,0.522876,0.572383,0.604088,0.235705,0.485542,0.548445,150.0
150,Zimbabwe,3.2992,1.972317,0.425564,1.047835,0.375038,0.377405,0.151349,0.080929,0.841031,151.0
151,South Sudan,2.8166,1.972317,0.289083,0.553279,0.208809,0.065609,0.209935,0.111157,1.378751,152.0
152,Afghanistan,2.5669,1.972317,0.300706,0.356434,0.266052,0.000000,0.135235,0.001226,1.507236,153.0

In [32]:
cols_20 = clean_df_2020.columns.tolist()
cols_20.insert(1, cols_20.pop(cols_20.index('Happiness Rank')))
clean_df_2020 = clean_df_2020.reindex(columns= cols_20)
clean_df_2020.head()

,Country,Happiness Rank,Happiness Score,Ladder score in Dystopia,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Dystopia Residual
0,Finland,1.0,7.8087,1.972317,1.285190,1.499526,0.961271,0.662317,0.159670,0.477857,2.762835
1,Denmark,2.0,7.6456,1.972317,1.326949,1.503449,0.979333,0.665040,0.242793,0.495260,2.432741
2,Switzerland,3.0,7.5599,1.972317,1.390774,1.472403,1.040533,0.628954,0.269056,0.407946,2.350267
3,Iceland,4.0,7.5045,1.972317,1.326502,1.547567,1.000843,0.661981,0.362330,0.144541,2.460688
4,Norway,5.0,7.4880,1.972317,1.424207,1.495173,1.008072,0.670201,0.287985,0.434101,2.168266

In [ ]:
# Clean Datasets: clean_df_2015, clean_df_2016, clean_df_2017, clean_df_2018, clean_df_2019, clean_df_2020